### ISSUE TITLE
Upload multiple files in one go

### ISSUE THREAD

**Issue by zxxc** [Smartling/api-sdk-net#10]
Upload multiply files in one go
As we have a lot of files (10000)
We need to start a lot of threads in parallel

And i found that if we are starting more than 300 requests we will receive some unexpected errors (not only 429, sometimes 500)
Would be good if library will have possibiliy for GetFileStatus, UploadFileContents, GetFile to work with multiply files. 

For instance, UploadFileContents(new [] {{
fileName:'someFile1.json',
fileContents:'{some json string}'
}, file2, file...},

For UploadFileContentswe received exceptions that we can't start more than 300 requests, but after some time I saw message for GetFile that we can't start more than 100 requests at the same time

**Comment by dimitrystd** [comment]
Well, i believe that file uploading in parallel or sequentially and reaction on errors is part of your business logic. I can agree with improvements like:
- make sdk threadsafe
- implement default handler for 429 error (repeat request after X seconds)

But for everything else you can create a wrapper around SDK and implement any business logic that fits your needs.

I'm just curious, what type of integration you build? This SDK was built primarily for Sitecore integration and no one else used it for 4 years.

**Comment by enegron-sl** [comment]
@zxxc Having 10K *resource* files for a  web site/app localization is unusual.  
What kind of content is in your database? UI strings or is it copy for your web site / app?  What is your tech stack?  Are you using a standard localization library?

**Comment by zxxc** [comment]
one resource is a object with 3-5 lines to translate and list of required languages
we have a few web sites and few mobile app
And one database where we are storing only translations

**Comment by dimitrystd** [comment]
Closed it as outdated.
