### ISSUE TITLE
AuditLog class contains too many details of sitecore integration

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/api-sdk-net#12]
_Follow up for https://github.com/Smartling/sitecore-localization-module/issues/519_

I would like to keep SDK generic (not as primary SDK for sitecore connector). The new [AuditLog.cs](https://github.com/Smartling/api-sdk-net/blob/b87c69dc8dd0407caf145592f169445d2dbc0376/Smartling.API/Model/AuditLog.cs) contains fields that are related to sitecore only.
Smartling audit API has single mandatory `time` field. So i think SDK should be responsible for:
* Authentication - it's existing basic functionality
* Validation - that SDK consumer provided at least `projectUid` and `time`
* Prepare and execute REST calls. It includes proper escaping and pagination if required

Everything else (fields) should be optional and come from consumer (sitecore connector). In this case SDK will not force user to use recommended field names but it's payback for "generic" implementation.

**Comment by dotnetrocks** [comment]
Merged.
