### ISSUE TITLE
Update SDK to File API v2

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/api-sdk-net#2]
Smartling File API v2 will be released soon. SDK should be ready for this release.

**DoD**: 
* Cover in SDK mandatory methods:
 * [x] Upload file
 * [x] Download file
 * [x] File Status (for locale)
 * [x] File Status (for all locales)
 * [x] Last modified (for locale)
 * [x] Last modified (for all locales)
 * [x] Authorize Locales
 * [x] Un-authorize Locales
 * [x] Delete File
 * [x] List Files
* Each subtask above includes:
 * Unit tests
 * Integration test
* Implemented new authentication flow via API gateway
 * [x] OAuth flow
 * [x] Caching `refresh_token` and `access_token`
 * [x] Request new token in case of expiration or 401
* [x] Sample app is updated
* [x] New version is published in nuget

**Note**:
Please keep in mind that scope of this task only about FAPI, but this sdk will also contain implementations for Projects and Jobs APIs.

**Comment by dimitrystd** [comment]
We had some discussions for java, probably it will be useful https://github.com/Smartling/api-sdk-java/issues/24. Also pls look and java sdk implementation

**Comment by dotnetrocks** [comment]
I suppose the "List" and "Delete" methods are also mandatory, right?

**Comment by dotnetrocks** [comment]
Also, the project is not on Nuget now, I'll upload it.

**Comment by dimitrystd** [comment]
Yes, let's implement them. We don't know who uses sdk except connectors, but it will be convenient to have them

**Comment by dotnetrocks** [comment]
Done & uploaded to Nuget: https://www.nuget.org/packages/Smartling.Api/
There might be some tweaks during integration with Sitecore Connector.

I did not implement Builder pattern / Async (mentioned in Java thread). Please reopen if it is needed.

Sample app updated & it can now use env. variables instead of entering token/secret each time.
