### ISSUE TITLE
Update signature of BatchApiClient.UploadFile

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/api-sdk-net#20]
I debugged something and noticed something weird in `BatchApiClient.UploadFile()`
* Remove `authorizeContent`. We don't need it because batch itself has `CreateBatch.authorize`
* Replace `string approvedLocales` with `IEnumerable<string>`. User may not know how to concat locales and it will make code clean in sitecore.

**Comment by dotnetrocks** [comment]
@dimitrystd Done, see PR. We probably need Major version update for it.
