### ISSUE TITLE
Ampersand in fileUri is not escaped correctly

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/api-sdk-net#21]
**Steps**:
* Upload file with name `D & G.xml`
* Now call `GetLastModified` with fileUri above

**Actual**:
You will get error
```json
{
    "response": {
        "code": "VALIDATION_ERROR",
        "errors": [
            {
                "key": "unknown.field",
                "message": "The field  G.xml was not expected. Please consult the documentation to verify the fields you are submitting.",
                "details": {
                    "field": " G.xml"
                }
            },
            {
                "key": "file.not.found",
                "message": "The file \"D \" could not be found",
                "details": {
                    "field": "fileUri"
                }
            }
        ]
    }
}
```
This is because smartling got 
```
https://api.stg.smartling.net/files-api/v2/projects/xxx/file/last-modified?fileUri=D%20&%20G.xml
```
You may notice that only spaces were urlencoded by `&` is unencoded. As result FAPI thinks that you send 2 parameters
* `fileUri=D%20`
* `%20G.xml`

**DoD**:
* Escape parameter names and values for ALL GET queries (not only for FAPI)
All APIs that use `PrepareGetRequest()` method
* Update `GetRequestStringBuilder` with using `Uri` class instead of just concat strings. We must be sure that result URL will be correct and doesn't depend on what user saved in configuration (leading\trailing slaches)
* Write tests that verify webrequest uses properly escaped parameters.
I added `ShouldEscapeParametersInLastModified` but it test `PrepareGetRequest()` which is not correct. Ideally we should test `WebRequest` that is returned by `PrepareGetRequest()`

**Comment by dotnetrocks** [comment]
@dimitrystd So is it still open or closed?

**Comment by dimitrystd** [comment]
I closed it but ideally we should fix other places and add tests
