### ISSUE TITLE
Extend File API to allow to upload content as string or stream

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/api-sdk-net#3]
Current implementation of `FileApiClient.UploadFile()` forces us to use real files as payload. But in most cases i have content as string or as stream. No sense to force developer to use temporary files.

**DoD**: New api version allows to upload content without creating a tmp file. Following types must be supported:
- String
- Stream

**Comment by dimitrystd** [comment]
I think it's good time to make breaking changes (new major SDK version)

**Comment by dotnetrocks** [comment]
Done, published to Nuget as 2.0.6
