### ISSUE TITLE
Switch SDK to use TLS 1.2

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/api-sdk-net#6]
From client
> We frequently start getting the following error from the connector.  The error occurs occasionally in production. We are able to “fix” this by doing an IIS reset but I wanted to ask if you have run into this before and if there is anything we can do to prevent this error:
```
1396 11:39:05 ERROR Failed to request file status
Exception: System.Net.WebException
Message: The request was aborted: Could not create SSL/TLS secure channel.
Source: System
   at System.Net.HttpWebRequest.GetResponse()
   at Smartling.Api.Translator.GetResponse(WebRequest request)
   at Smartling.Api.Translator.GetFileStatus(String fileUri, String locale)
   at Smartling.Connector.Translation.Status.StatusManager.QueryStatus(QueuedItem queuedItem)
```

I googled it, but didn't find anything else except to update
```
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12; 
```
in https://github.com/Smartling/api-sdk-net/blob/master/Smartling.API/ApiClientBase.cs

**Comment by dimitrystd** [comment]
This task becomes a blocker. Smartling is going to deprecate TLSv1, so all incoming connections will be rejected.

**Comment by dotnetrocks** [comment]
@dimitrystd Done.
