### ISSUE TITLE
Add support for dotnetcore

### ISSUE THREAD

**Issue by zxxc** [Smartling/api-sdk-net#8]
Hi, we want to use this package in dotnet core project
So, please make it compatible

`warning NU1701: Package 'Smartling.Api 2.2.7' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.`

**Comment by dotnetrocks** [comment]
@dimitrystd Done. Project recreated with multi-targeting (.net 4.5 and .netstandard2.0).
